In [1]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import requests
from datetime import datetime

raw= requests.get("https://services1.arcgis.com/0MSEUqKaxRlEPj5g/arcgis/rest/services/Coronavirus_2019_nCoV_Cases/FeatureServer/1/query?where=1%3D1&outFields=*&outSR=4326&f=json")
raw_json = raw.json()
df = pd.DataFrame(raw_json["features"])

In [2]:
df.head()

,attributes,geometry
0,"{'OBJECTID': 1, 'Province_State': 'Abruzzo', '...","{'x': 13.398438230000068, 'y': 42.35122196000003}"
1,"{'OBJECTID': 2, 'Province_State': 'Acre', 'Cou...","{'x': -70.81199999999995, 'y': -9.023799999999..."
2,"{'OBJECTID': 3, 'Province_State': 'Aguascalien...","{'x': -102.29159999999996, 'y': 21.88530000000..."
3,"{'OBJECTID': 4, 'Province_State': 'Aichi', 'Co...","{'x': 137.21162100000004, 'y': 35.035551000000..."
4,"{'OBJECTID': 5, 'Province_State': 'Akita', 'Co...","{'x': 140.408228, 'y': 39.74867900000004}"

In [3]:
df["attributes"][0]

{'OBJECTID': 1,
 'Province_State': 'Abruzzo',
 'Country_Region': 'Italy',
 'Last_Update': 1590852769000,
 'Lat': 42.35122196,
 'Long_': 13.39843823,
 'Confirmed': 3237,
 'Recovered': 2063,
 'Deaths': 404}

In [4]:
data_list = df["attributes"].tolist()
df_final = pd.DataFrame(data_list)
df_final.set_index("OBJECTID")
df_final = df_final[["Country_Region", "Province_State", "Lat", "Long_", "Confirmed", "Deaths", "Recovered", "Last_Update"]]

In [5]:
df_final.head()

,Country_Region,Province_State,Lat,Long_,Confirmed,Deaths,Recovered,Last_Update
0,Italy,Abruzzo,42.351222,13.398438,3237,404,2063,1.590853e+12
1,Brazil,Acre,-9.023800,-70.812000,5841,135,0,1.590853e+12
2,Mexico,Aguascalientes,21.885300,-102.291600,797,33,545,1.590853e+12
3,Japan,Aichi,35.035551,137.211621,507,34,455,1.590853e+12
4,Japan,Akita,39.748679,140.408228,16,0,16,1.590853e+12

In [6]:
def convertTime(t):
    t = int(t)
    return datetime.fromtimestamp(t)

df_final = df_final.dropna(subset=["Last_Update"])
df_final["Province_State"].fillna(value="", inplace=True)

df_final["Last_Update"]= df_final["Last_Update"]/1000
df_final["Last_Update"] = df_final["Last_Update"].apply(convertTime)

df_final.head()

,Country_Region,Province_State,Lat,Long_,Confirmed,Deaths,Recovered,Last_Update
0,Italy,Abruzzo,42.351222,13.398438,3237,404,2063,2020-05-30 12:32:49
1,Brazil,Acre,-9.023800,-70.812000,5841,135,0,2020-05-30 12:32:49
2,Mexico,Aguascalientes,21.885300,-102.291600,797,33,545,2020-05-30 12:32:49
3,Japan,Aichi,35.035551,137.211621,507,34,455,2020-05-30 12:32:49
4,Japan,Akita,39.748679,140.408228,16,0,16,2020-05-30 12:32:49

In [7]:
df_final= df_final[df_final['Country_Region'] == 'Brazil']

In [8]:
df_total = df_final[df_final['Country_Region'] == 'Brazil']

In [9]:
df_total.dropna(inplace=True)

In [10]:
df_total['Confirmed'].sum()

465166

In [11]:
total_confirmed = df_final["Confirmed"].sum()
total_recovered = df_final["Recovered"].sum()
total_deaths = df_final["Deaths"].sum()

In [12]:
df_top10 = df_total.nlargest(10, "Confirmed")
top10_countries_1 = df_top10["Province_State"].tolist()
top10_confirmed = df_top10["Confirmed"].tolist()

df_top10 = df_total.nlargest(10, "Recovered")
top10_countries_2 = df_top10["Province_State"].tolist()
top10_recovered = df_top10["Recovered"].tolist()

df_top10 = df_total.nlargest(10, "Deaths")
top10_countries_3 = df_top10["Province_State"].tolist()
top10_deaths = df_top10["Deaths"].tolist()

In [13]:
fig = make_subplots(
    rows = 4, cols = 6,

    specs=[
            [{"type": "scattergeo", "rowspan": 4, "colspan": 3}, None, None, {"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"} ],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,              {"type": "bar", "colspan":3}, None, None],
            [    None, None, None,               {"type": "bar", "colspan":3}, None, None],
          ]
)


message = df_total["Country_Region"] + " " + df_total["Province_State"] + "<br>"
message += "Confirmed: " + df_total["Confirmed"].astype(str) + "<br>"
message += "Deaths: " + df_total["Deaths"].astype(str) + "<br>"
message += "Recovered: " + df_total["Recovered"].astype(str) + "<br>"
message += "Last updated: " + df_total["Last_Update"].astype(str)
df_final["text"] = message

fig.add_trace(
    go.Scattergeo(
        lon = df_final["Long_"],
        lat = df_final["Lat"],
        hovertext = df_final["text"],
        showlegend=False,
        marker = dict(
            size = df_final["Confirmed"]/(df_final["Confirmed"].max())*70,
            opacity = 0.8,
            reversescale = True,
            autocolorscale = True,
            #symbol = 'square',
            line = dict(
                width=1,
                color='rgba(102, 102, 102)'
            ),
            cmin = 0,
            color = df_final['Confirmed'],
            cmax = df_final['Confirmed'].max(),
            colorbar_title="Confirmed Cases<br>Latest Update",  
            colorbar_x = -0.05
        )

    ),
    
    row=1, col=1
)

fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_confirmed,
        title="Confirmed Cases",
    ),
    row=1, col=4
)



fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_deaths,
        title="Deaths Cases",
    ),
    row=1, col=6
)

fig.add_trace(
    go.Bar(
        x=top10_countries_1,
        y=top10_confirmed, 
        name= "Confirmed Cases",
        marker=dict(color="Yellow"), 
        showlegend=True,
    ),
    row=2, col=4
)


fig.add_trace(
    go.Bar(
        x=top10_countries_3,
        y=top10_deaths, 
        name= "Deaths Cases",
        marker=dict(color="crimson"), 
        showlegend=True),
    row=4, col=4
)


fig.update_layout(
    template="plotly",
    title = "Casos de COVID-19 no Brasil (Última atualização: " + str(df_final["Last_Update"][1]) + ")",
    showlegend=True,
    legend_orientation="h",
    legend=dict(x=0.65, y=0.85),
    geo_scope='south america',
    geo = dict(
            #projection_type="orthographic",
            showcoastlines=True,
            landcolor="white", 
            showland= True,
            showocean = True,
            lakecolor="LightBlue"
    ),

    annotations=[
        dict(
            text="Source: https://bit.ly/3aEzxjK",
            showarrow=False,
            xref="paper",
            yref="paper",
            x=0.35,
            y=0)
    ]
)

fig.write_html('first_figure.html', auto_open=True)